### ISSUE TITLE
Unable to set permissions for Windows File System

### ISSUE THREAD

**Issue by FelixDev0518** [googleworkspace/java-samples#112]
(Please fill out these details before submitting an issue)

### Sample Name
(i.e. Gmail Quickstart)
Google Sheets API v4 Sample Code in Java
### Expected Behavior
Access to the Google Spread Sheet
### Specifications
  - Java version (`15`)
  - OS (Windows 10)

### Log
com.google.api.client.util.store.FileDataStoreFactory setPermissionsToOwnerOnly
WARNING: Unable to set permissions for C:\Users\**\**\logindemo2\tokens, because you are running on a non-POSIX file system.
Exception in thread "main" com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Unable to parse range: Sheet1!A2:A4",
    "reason" : "badRequest"
  } ],
  "message" : "Unable to parse range: Sheet1!A2:A4",
  "status" : "INVALID_ARGUMENT"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:443)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1108)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:541)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:474)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:591)
	at com.example.logindemo2.SheetBot.main(SheetBot.java:152)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':SheetBot.main()'.
> Process 'command 'C:/Program Files/Java/jdk-15.0.1/bin/java.exe'' finished with non-zero exit value 1

**Comment by boatrainlsz** [comment]
I got same issue
