### ISSUE TITLE
Java quickstart for Google Drive: java.net.BindException: Address already in use: bind

### ISSUE THREAD

**Issue by Anton-V-K** [googleworkspace/java-samples#431]
# Summary

When running [Java quickstart](https://developers.google.com/drive/api/quickstart/java) (with minimal changes - renaming the class and .json with credentials) I get the exception `java.net.BindException: Address already in use: bind`

## Sample Name

[Java quickstart](https://developers.google.com/drive/api/quickstart/java)

## Expected Behavior

It should run without exceptions

## Actual Behavior

```
...\GoogleDriveTool>gradlew run

> Task :run FAILED
Exception in thread "main" java.net.BindException: Address already in use: bind
  at java.base/sun.nio.ch.Net.bind0(Native Method)
  at java.base/sun.nio.ch.Net.bind(Net.java:555)
  at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
  at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
  at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
  at jdk.httpserver/sun.net.httpserver.ServerImpl.<init>(ServerImpl.java:101)
  at jdk.httpserver/sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java:50)
  at jdk.httpserver/sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35)
  at jdk.httpserver/com.sun.net.httpserver.HttpServer.create(HttpServer.java:150)
  at com.google.api.client.extensions.jetty.auth.oauth2.LocalServerReceiver.getRedirectUri(LocalServerReceiver.java:127)
  at com.google.api.client.extensions.java6.auth.oauth2.AuthorizationCodeInstalledApp.authorize(AuthorizationCodeInstalledApp.java:109)
  at GoogleDriveTool.getCredentials(GoogleDriveTool.java:70)
  at GoogleDriveTool.main(GoogleDriveTool.java:78)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk-17.0.2\bin\java.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
3 actionable tasks: 1 executed, 2 up-to-date
```
## Specifications

- Java version:
```
D:\Anton\Devel\java-dev\GoogleDriveTool>java -version
java version "17.0.2" 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)
```
- OS: Windows 10 21H1 (Version 10.0.19043 Build 19043)

**Comment by Anton-V-K** [comment]
The issue is in `getCredentials` - it uses the port `8888` (for authorization callback) which is by coincidence used by Resilio Sync web-interface.
The quick fix is simple - replace the port number with another one which isn't used on your PC (like `9999`):
```
  private static Credential getCredentials(final NetHttpTransport HTTP_TRANSPORT)
      throws IOException {
    // Load client secrets.
    // ...
    LocalServerReceiver receiver = new LocalServerReceiver.Builder().setPort(9999).build();
    Credential credential = new AuthorizationCodeInstalledApp(flow, receiver).authorize("user");
    //returns an authorized Credential object.
    return credential;
  }
```
